name = "GBA"
uuid = "718d6770-468c-4493-aba4-08cae91b8107"
authors = ["Brian D. Klahn <briandk@virginia.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
